import { createApp } from 'vue';
import router from './routes/index';
import './styles/index.css';
import App from './App.vue';
import Jumbotron from './components/Jumbotron.vue';
import AppInput from './components/shared/inputs/AppInput.vue';
import AppTextArea from './components/shared/inputs/AppTextArea.vue';
import FormButton from './components/shared/buttons/Form.vue';
import ClientError from './components/shared/errors/ClientError.vue';
import ServerError from './components/shared/errors/ServerError.vue';

const app = createApp(App);
app.use(router);
app.component('Jumbotron', Jumbotron);
app.component('AppInput', AppInput);
app.component('AppTextArea', AppTextArea);
app.component('FormButton', FormButton);
app.component('ClientError', ClientError);
app.component('ServerError', ServerError);
app.mount('#app');
